#!/bin/bash

#deal data
#python preprocess.py --source-lang ti --target-lang zh --trainpref ../../../data/CCMT2019/data_20191101/charTi_charZh/train --validpref ../../../data/CCMT2019/data_20191101/charTi_charZh/valid --testpref ../../../data/CCMT2019/data_20191101/charTi_charZh/test-2017 --destdir mydata/data-bin/charTi_charZh --workers 5

#python preprocess.py --source-lang ti --target-lang zh --trainpref ../../../data/CCMT2019/data_20191101/charTi_wordZh/train --validpref ../../../data/CCMT2019/data_20191101/charTi_wordZh/valid --testpref ../../../data/CCMT2019/data_20191101/charTi_wordZh/test-2017 --destdir mydata/data-bin/charTi_wordZh --workers 5

#python preprocess.py --source-lang ti --target-lang zh --trainpref ../../../data/CCMT2019/data_20191101/wordTi_wordZh/train --validpref ../../../data/CCMT2019/data_20191101/wordTi_wordZh/valid --testpref ../../../data/CCMT2019/data_20191101/wordTi_wordZh/test-2017 --destdir mydata/data-bin/wordTi_wordZh --workers 5

#python preprocess.py --source-lang ti --target-lang zh --trainpref ../../../data/CCMT2019/data_20191105/charTi_charZh/train --validpref ../../../data/CCMT2019/data_20191105/charTi_charZh/valid --testpref ../../../data/CCMT2019/data_20191105/charTi_charZh/test-2017 --destdir mydata/data-bin/charTi_charZh_new --workers 5

#python preprocess.py --source-lang ti --target-lang zh --trainpref ../../../data/CCMT2019/data_20191105/charTi_wordZh/train --validpref ../../../data/CCMT2019/data_20191105/charTi_wordZh/valid --testpref ../../../data/CCMT2019/data_20191105/charTi_wordZh/test-2017 --destdir mydata/data-bin/charTi_wordZh_new --workers 5

#python preprocess.py --source-lang ti --target-lang zh --trainpref ../../../data/CCMT2019/data_20191105/wordTi_wordZh/train --validpref ../../../data/CCMT2019/data_20191105/wordTi_wordZh/valid --testpref ../../../data/CCMT2019/data_20191105/wordTi_wordZh/test-2017 --destdir mydata/data-bin/wordTi_wordZh_new --workers 5


#train transformer model
#---------------Exp1-------------------
#CUDA_VISIBLE_DEVICES=0 python train.py mydata/data-bin/charTi_charZh_new --arch transformer_iwslt_de_en --save-dir checkpoints/charChar_exp1 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 --dropout 0.3 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096
#CUDA_VISIBLE_DEVICES=1 python train.py mydata/data-bin/charTi_wordZh_new --arch transformer_iwslt_de_en --save-dir checkpoints/charWord_exp1 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 --dropout 0.3 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096
#CUDA_VISIBLE_DEVICES=2 python train.py mydata/data-bin/wordTi_wordZh_new --arch transformer_iwslt_de_en --save-dir checkpoints/wordWord_exp1 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 --dropout 0.3 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096

#--------------Exp2----------------------
#CUDA_VISIBLE_DEVICES=0 python train.py mydata/data-bin/charTi_charZh_new --arch transformer_wmt_en_de --save-dir checkpoints/charChar_exp2 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096
#CUDA_VISIBLE_DEVICES=1 python train.py mydata/data-bin/charTi_wordZh_new --arch transformer_wmt_en_de --save-dir checkpoints/charWord_exp2 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096
#CUDA_VISIBLE_DEVICES=2 python train.py mydata/data-bin/wordTi_wordZh_new --arch transformer_wmt_en_de --save-dir checkpoints/wordWord_exp2 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096

#---------------Exp3-----------------------
#CUDA_VISIBLE_DEVICES=0 python train.py mydata/data-bin/charTi_charZh_new --arch transformer_wmt_en_de --save-dir checkpoints/charChar_exp3 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 8000 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096
#CUDA_VISIBLE_DEVICES=1 python train.py mydata/data-bin/charTi_wordZh_new --arch transformer_wmt_en_de --save-dir checkpoints/charWord_exp3 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 8000 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096
#CUDA_VISIBLE_DEVICES=2 python train.py mydata/data-bin/wordTi_wordZh_new --arch transformer_wmt_en_de --save-dir checkpoints/wordWord_exp3 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 8000 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096

#---------------Exp4-----------------------
#CUDA_VISIBLE_DEVICES=0 python train.py mydata/data-bin/charTi_charZh_new --arch transformer_wmt_en_de --save-dir checkpoints/charChar_exp4 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 8000 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 --dropout 0.3
#CUDA_VISIBLE_DEVICES=1 python train.py mydata/data-bin/charTi_wordZh_new --arch transformer_wmt_en_de --save-dir checkpoints/charWord_exp4 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 8000 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 --dropout 0.3
#CUDA_VISIBLE_DEVICES=2 python train.py mydata/data-bin/wordTi_wordZh_new --arch transformer_wmt_en_de --save-dir checkpoints/wordWord_exp4 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 --dropout 0.3

#---------------Exp5-----------------------
#CUDA_VISIBLE_DEVICES=0 python train.py mydata/data-bin/charTi_charZh_new --arch transformer_iwslt_de_en --save-dir checkpoints/charChar_exp5 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096
#CUDA_VISIBLE_DEVICES=1 python train.py mydata/data-bin/charTi_wordZh_new --arch transformer_iwslt_de_en --save-dir checkpoints/charWord_exp5 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096
#CUDA_VISIBLE_DEVICES=2 python train.py mydata/data-bin/wordTi_wordZh_new --arch transformer_iwslt_de_en --save-dir checkpoints/wordWord_exp5 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096

CUDA_VISIBLE_DEVICES=3 python train.py mydata/data-bin/wordTi_wordZh_new --arch transformer_iwslt_de_en --save-dir checkpoints/test --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096


#evaluate experiment model
#CUDA_VISIBLE_DEVICES=7 python generate.py data/data-bin/charCCMT --task translation --log-format simple --log-interval 10 --path result/exp2/checkpoint_last.pt --batch-size 128 --beam 5 --remove-bpe --results-path temp

