#!/bin/bash

#deal data
python preprocess.py --source-lang zh --target-lang en --trainpref data_zhen/train --validpref data_zhen/val --testpref data_zhen/test --destdir mydata/data-bin/zhen --workers 5

#python preprocess.py --source-lang ti --target-lang zh --trainpref ../../../data/CCMT2019/data_20191126/charTi_wordZh/train --validpref ../../../data/CCMT2019/data_20191126/charTi_wordZh/valid --testpref ../../../data/CCMT2019/data_20191126/charTi_wordZh/test-2017 --destdir mydata/data-bin/charTi_wordZh_v2 --workers 5

#python preprocess.py --source-lang ti --target-lang zh --trainpref ../../../data/CCMT2019/data_20191126/wordTi_wordZh/train --validpref ../../../data/CCMT2019/data_20191126/wordTi_wordZh/valid --testpref ../../../data/CCMT2019/data_20191126/wordTi_wordZh/test-2017 --destdir mydata/data-bin/wordTi_wordZh_v2 --workers 5

#python preprocess.py --source-lang ti --target-lang zh --trainpref ../../../data/CCMT2019/data_20191105/charTi_charZh/train --validpref ../../../data/CCMT2019/data_20191105/charTi_charZh/valid --testpref ../../../data/CCMT2019/data_20191105/charTi_charZh/test-2017 --destdir mydata/data-bin/charTi_charZh_new --workers 5

#python preprocess.py --source-lang ti --target-lang zh --trainpref ../../../data/CCMT2019/data_20191105/charTi_wordZh/train --validpref ../../../data/CCMT2019/data_20191105/charTi_wordZh/valid --testpref ../../../data/CCMT2019/data_20191105/charTi_wordZh/test-2017 --destdir mydata/data-bin/charTi_wordZh_new --workers 5

#python preprocess.py --source-lang ti --target-lang zh --trainpref ../../../data/CCMT2019/data_20191105/wordTi_wordZh/train --validpref ../../../data/CCMT2019/data_20191105/wordTi_wordZh/valid --testpref ../../../data/CCMT2019/data_20191105/wordTi_wordZh/test-2017 --destdir mydata/data-bin/wordTi_wordZh_new --workers 5


#train transformer model
#---------------Exp1-------------------
#CUDA_VISIBLE_DEVICES=0 python train.py mydata/data-bin/charTi_charZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/charChar_exp1 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 --dropout 0.3 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096
#CUDA_VISIBLE_DEVICES=1 python train.py mydata/data-bin/charTi_wordZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/charWord_exp1 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 --dropout 0.3 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096
#CUDA_VISIBLE_DEVICES=2 python train.py mydata/data-bin/wordTi_wordZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/wordWord_exp1 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 --dropout 0.3 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096

#--------------Exp2----------------------
#CUDA_VISIBLE_DEVICES=0 python train.py mydata/data-bin/charTi_charZh_v2 --arch transformer_wmt_en_de --save-dir checkpoints/charChar_exp2 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096
#CUDA_VISIBLE_DEVICES=1 python train.py mydata/data-bin/charTi_wordZh_v2 --arch transformer_wmt_en_de --save-dir checkpoints/charWord_exp2 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096
#CUDA_VISIBLE_DEVICES=2 python train.py mydata/data-bin/wordTi_wordZh_v2 --arch transformer_wmt_en_de --save-dir checkpoints/wordWord_exp2 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096

#---------------Exp3-----------------------
#CUDA_VISIBLE_DEVICES=0 python train.py mydata/data-bin/charTi_charZh_v2 --arch transformer_wmt_en_de --save-dir checkpoints/charChar_exp3 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 8000 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096
#CUDA_VISIBLE_DEVICES=1 python train.py mydata/data-bin/charTi_wordZh_v2 --arch transformer_wmt_en_de --save-dir checkpoints/charWord_exp3 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 8000 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096
#CUDA_VISIBLE_DEVICES=2 python train.py mydata/data-bin/wordTi_wordZh_v2 --arch transformer_wmt_en_de --save-dir checkpoints/wordWord_exp3 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 8000 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096

#---------------Exp4-----------------------
#CUDA_VISIBLE_DEVICES=0 python train.py mydata/data-bin/charTi_charZh_v2 --arch transformer_wmt_en_de --save-dir checkpoints/charChar_exp4 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 8000 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 --dropout 0.3
#CUDA_VISIBLE_DEVICES=1 python train.py mydata/data-bin/charTi_wordZh_v2 --arch transformer_wmt_en_de --save-dir checkpoints/charWord_exp4 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 8000 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 --dropout 0.3
#CUDA_VISIBLE_DEVICES=2 python train.py mydata/data-bin/wordTi_wordZh_v2 --arch transformer_wmt_en_de --save-dir checkpoints/wordWord_exp4 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 --dropout 0.3

#---------------Exp5-----------------------
#CUDA_VISIBLE_DEVICES=0 python train.py mydata/data-bin/charTi_charZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/charChar_exp5 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096
#CUDA_VISIBLE_DEVICES=1 python train.py mydata/data-bin/charTi_wordZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/charWord_exp5 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096
#CUDA_VISIBLE_DEVICES=2 python train.py mydata/data-bin/wordTi_wordZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/wordWord_exp5 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096

#---------------Exp6-----------------------
#CUDA_VISIBLE_DEVICES=0 python train.py mydata/data-bin/charTi_charZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/charChar_exp6 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 8000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096
#CUDA_VISIBLE_DEVICES=1 python train.py mydata/data-bin/charTi_wordZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/charWord_exp6 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 8000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096
#CUDA_VISIBLE_DEVICES=2 python train.py mydata/data-bin/wordTi_wordZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/wordWord_exp6 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 8000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096

#---------------Exp7-----------------------
#CUDA_VISIBLE_DEVICES=0 python train.py mydata/data-bin/charTi_charZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/charChar_exp7 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 16000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096
#CUDA_VISIBLE_DEVICES=1 python train.py mydata/data-bin/charTi_wordZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/charWord_exp7 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 16000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096
#CUDA_VISIBLE_DEVICES=2 python train.py mydata/data-bin/wordTi_wordZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/wordWord_exp7 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 16000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096

#---------------Exp8-----------------------
#CUDA_VISIBLE_DEVICES=0 python train.py mydata/data-bin/charTi_charZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/charChar_exp8 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 8000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 --encoder-layers 1 --decoder-layers 1 --encoder-ffn-embed-dim 1024 --decoder-ffn-embed-dim 1024
#CUDA_VISIBLE_DEVICES=1 python train.py mydata/data-bin/charTi_wordZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/charWord_exp8 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 8000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 --encoder-layers 1 --decoder-layers 1 --encoder-ffn-embed-dim 1024 --decoder-ffn-embed-dim 1024
#CUDA_VISIBLE_DEVICES=2 python train.py mydata/data-bin/wordTi_wordZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/wordWord_exp8 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 8000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 --encoder-layers 1 --decoder-layers 1 --encoder-ffn-embed-dim 1024 --decoder-ffn-embed-dim 1024

#---------------Exp9-----------------------
#CUDA_VISIBLE_DEVICES=0 python train.py mydata/data-bin/charTi_charZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/charChar_exp9 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 16000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 --encoder-layers 1 --decoder-layers 1 --encoder-ffn-embed-dim 1024 --decoder-ffn-embed-dim 1024
#CUDA_VISIBLE_DEVICES=1 python train.py mydata/data-bin/charTi_wordZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/charWord_exp9 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 16000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 --encoder-layers 1 --decoder-layers 1 --encoder-ffn-embed-dim 1024 --decoder-ffn-embed-dim 1024
#CUDA_VISIBLE_DEVICES=2 python train.py mydata/data-bin/wordTi_wordZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/wordWord_exp9 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 16000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 --encoder-layers 1 --decoder-layers 1 --encoder-ffn-embed-dim 1024 --decoder-ffn-embed-dim 1024

#---------------Exp10-----------------------
#CUDA_VISIBLE_DEVICES=0 python train.py mydata/data-bin/charTi_charZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/charChar_exp10 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 --encoder-layers 1 --decoder-layers 1 --encoder-ffn-embed-dim 1024 --decoder-ffn-embed-dim 1024
#CUDA_VISIBLE_DEVICES=1 python train.py mydata/data-bin/charTi_wordZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/charWord_exp10 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 --encoder-layers 1 --decoder-layers 1 --encoder-ffn-embed-dim 1024 --decoder-ffn-embed-dim 1024
#CUDA_VISIBLE_DEVICES=2 python train.py mydata/data-bin/wordTi_wordZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/wordWord_exp10 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 --encoder-layers 1 --decoder-layers 1 --encoder-ffn-embed-dim 1024 --decoder-ffn-embed-dim 1024

#---------------Exp11-----------------------
#CUDA_VISIBLE_DEVICES=0 python train.py mydata/data-bin/charTi_charZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/charChar_exp11 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 8000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 --encoder-layers 1 --decoder-layers 1 --encoder-ffn-embed-dim 1024 --decoder-ffn-embed-dim 1024 --lr 0.0001
#CUDA_VISIBLE_DEVICES=1 python train.py mydata/data-bin/charTi_wordZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/charWord_exp11 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 8000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 --encoder-layers 1 --decoder-layers 1 --encoder-ffn-embed-dim 1024 --decoder-ffn-embed-dim 1024 --lr 0.0001
#CUDA_VISIBLE_DEVICES=2 python train.py mydata/data-bin/wordTi_wordZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/wordWord_exp11 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 8000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 --encoder-layers 1 --decoder-layers 1 --encoder-ffn-embed-dim 1024 --decoder-ffn-embed-dim 1024 --lr 0.0001

#---------------Exp12-----------------------
#CUDA_VISIBLE_DEVICES=0 python train.py mydata/data-bin/charTi_charZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/charChar_exp12 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 8000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 --encoder-layers 1 --decoder-layers 1 --encoder-ffn-embed-dim 1024 --decoder-ffn-embed-dim 1024 --lr 0.00005
#CUDA_VISIBLE_DEVICES=1 python train.py mydata/data-bin/charTi_wordZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/charWord_exp12 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 8000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 --encoder-layers 1 --decoder-layers 1 --encoder-ffn-embed-dim 1024 --decoder-ffn-embed-dim 1024 --lr 0.00005
#CUDA_VISIBLE_DEVICES=2 python train.py mydata/data-bin/wordTi_wordZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/wordWord_exp12 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 8000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 --encoder-layers 1 --decoder-layers 1 --encoder-ffn-embed-dim 1024 --decoder-ffn-embed-dim 1024 --lr 0.00005

#---------------Exp13-----------------------
#CUDA_VISIBLE_DEVICES=0 python train.py mydata/data-bin/charTi_charZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/charChar_exp13 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 8000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 --encoder-layers 1 --decoder-layers 1 --encoder-ffn-embed-dim 1024 --decoder-ffn-embed-dim 1024 --lr 0.001
#CUDA_VISIBLE_DEVICES=1 python train.py mydata/data-bin/charTi_wordZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/charWord_exp13 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 8000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 --encoder-layers 1 --decoder-layers 1 --encoder-ffn-embed-dim 1024 --decoder-ffn-embed-dim 1024 --lr 0.001
#CUDA_VISIBLE_DEVICES=2 python train.py mydata/data-bin/wordTi_wordZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/wordWord_exp13 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 8000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 --encoder-layers 1 --decoder-layers 1 --encoder-ffn-embed-dim 1024 --decoder-ffn-embed-dim 1024 --lr 0.001

#---------------Exp14-----------------------
#CUDA_VISIBLE_DEVICES=0 python train.py mydata/data-bin/charTi_charZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/charChar_exp14 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 8000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 --encoder-layers 6 --decoder-layers 6 --encoder-ffn-embed-dim 1024 --decoder-ffn-embed-dim 1024 --lr 0.0001
#CUDA_VISIBLE_DEVICES=1 python train.py mydata/data-bin/charTi_wordZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/charWord_exp14 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 8000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 --encoder-layers 6 --decoder-layers 6 --encoder-ffn-embed-dim 1024 --decoder-ffn-embed-dim 1024 --lr 0.0001
#CUDA_VISIBLE_DEVICES=2 python train.py mydata/data-bin/wordTi_wordZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/wordWord_exp14 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 8000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 --encoder-layers 6 --decoder-layers 6 --encoder-ffn-embed-dim 1024 --decoder-ffn-embed-dim 1024 --lr 0.0001

#---------------Exp15-----------------------
#CUDA_VISIBLE_DEVICES=0 python train.py mydata/data-bin/charTi_charZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/charChar_exp15 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 8000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 --encoder-layers 6 --decoder-layers 6 --encoder-ffn-embed-dim 1024 --decoder-ffn-embed-dim 1024 --lr 0.00005
#CUDA_VISIBLE_DEVICES=1 python train.py mydata/data-bin/charTi_wordZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/charWord_exp15 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 8000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 --encoder-layers 6 --decoder-layers 6 --encoder-ffn-embed-dim 1024 --decoder-ffn-embed-dim 1024 --lr 0.00005
#CUDA_VISIBLE_DEVICES=2 python train.py mydata/data-bin/wordTi_wordZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/wordWord_exp15 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 8000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 --encoder-layers 6 --decoder-layers 6 --encoder-ffn-embed-dim 1024 --decoder-ffn-embed-dim 1024 --lr 0.00005

#---------------Exp16-----------------------
#CUDA_VISIBLE_DEVICES=0 python train.py mydata/data-bin/charTi_charZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/charChar_exp16 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 8000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 --encoder-layers 6 --decoder-layers 6 --encoder-ffn-embed-dim 1024 --decoder-ffn-embed-dim 1024 --lr 0.001
#CUDA_VISIBLE_DEVICES=1 python train.py mydata/data-bin/charTi_wordZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/charWord_exp16 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 8000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 --encoder-layers 6 --decoder-layers 6 --encoder-ffn-embed-dim 1024 --decoder-ffn-embed-dim 1024 --lr 0.001
#CUDA_VISIBLE_DEVICES=2 python train.py mydata/data-bin/wordTi_wordZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/wordWord_exp16 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 8000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 --encoder-layers 6 --decoder-layers 6 --encoder-ffn-embed-dim 1024 --decoder-ffn-embed-dim 1024 --lr 0.001

#---------------Exp17-----------------------
#CUDA_VISIBLE_DEVICES=0 python train.py mydata/data-bin/charTi_charZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/charChar_exp17 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 --encoder-layers 6 --decoder-layers 6 --encoder-ffn-embed-dim 1024 --decoder-ffn-embed-dim 1024 --lr 0.0001
#CUDA_VISIBLE_DEVICES=1 python train.py mydata/data-bin/charTi_wordZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/charWord_exp17 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 --encoder-layers 6 --decoder-layers 6 --encoder-ffn-embed-dim 1024 --decoder-ffn-embed-dim 1024 --lr 0.0001
#CUDA_VISIBLE_DEVICES=1 python train.py mydata/data-bin/wordTi_wordZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/wordWord_exp17 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 --encoder-layers 6 --decoder-layers 6 --encoder-ffn-embed-dim 1024 --decoder-ffn-embed-dim 1024 --lr 0.0001

#---------------Exp18-----------------------
#CUDA_VISIBLE_DEVICES=0 python train.py mydata/data-bin/charTi_charZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/charChar_exp18 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 --encoder-layers 6 --decoder-layers 6 --encoder-ffn-embed-dim 1024 --decoder-ffn-embed-dim 1024 --lr 0.00005
#CUDA_VISIBLE_DEVICES=1 python train.py mydata/data-bin/charTi_wordZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/charWord_exp18 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 --encoder-layers 6 --decoder-layers 6 --encoder-ffn-embed-dim 1024 --decoder-ffn-embed-dim 1024 --lr 0.00005
#CUDA_VISIBLE_DEVICES=0 python train.py mydata/data-bin/wordTi_wordZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/wordWord_exp18 --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 --encoder-layers 6 --decoder-layers 6 --encoder-ffn-embed-dim 1024 --decoder-ffn-embed-dim 1024 --lr 0.00005



#CUDA_VISIBLE_DEVICES=3 python train.py mydata/data-bin/wordTi_wordZh_v2 --arch transformer_iwslt_de_en --save-dir checkpoints/test --log-interval 300 --no-progress-bar --no-epoch-checkpoints --log-format simple --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096


#evaluate experiment model
#CUDA_VISIBLE_DEVICES=7 python generate.py data/data-bin/charCCMT --task translation --log-format simple --log-interval 10 --path result/exp2/checkpoint_last.pt --batch-size 128 --beam 5 --remove-bpe --results-path temp

#python preprocess.py --source-lang ti --target-lang zh --trainpref ../../../data/CCMT2019/data_20191126/charTi_charZh/train --validpref ../../../data/CCMT2019/data_20191126/charTi_charZh/valid --testpref ../../../data/CCMT2019/data_20191126/charTi_charZh/test-2017 --destdir mydata/test --workers 5


